from __future__ import annotations

from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas


PAGE_SIZE = (16 * inch, 9 * inch)
BLACK = colors.HexColor("#070707")
SOFT_BLACK = colors.HexColor("#121212")
GOLD = colors.HexColor("#D4AF37")
SOFT_GOLD = colors.HexColor("#F3D98B")


def _slugify(value: str) -> str:
    candidate = "".join(char.lower() if char.isalnum() else "_" for char in value)
    while "__" in candidate:
        candidate = candidate.replace("__", "_")
    return candidate.strip("_") or "song"


def _paint_background(pdf: canvas.Canvas, width: float, height: float) -> None:
    pdf.setFillColor(BLACK)
    pdf.rect(0, 0, width, height, stroke=0, fill=1)
    pdf.setFillColor(SOFT_BLACK)
    pdf.rect(0.3 * inch, 0.3 * inch, width - 0.6 * inch, height - 0.6 * inch, stroke=0, fill=1)
    pdf.setStrokeColor(GOLD)
    pdf.setLineWidth(2)
    pdf.rect(0.3 * inch, 0.3 * inch, width - 0.6 * inch, height - 0.6 * inch, stroke=1, fill=0)


def _draw_header(pdf: canvas.Canvas, title: str, subtitle: str, width: float, height: float) -> None:
    pdf.setFillColor(SOFT_GOLD)
    pdf.setFont("Helvetica-Bold", 32)
    pdf.drawString(0.8 * inch, height - 1.2 * inch, title)
    pdf.setFillColor(GOLD)
    pdf.setFont("Helvetica", 13)
    pdf.drawString(0.8 * inch, height - 1.65 * inch, subtitle)


def _draw_summary_table(pdf: canvas.Canvas, summary: dict, width: float, height: float) -> None:
    table_x = 0.8 * inch
    table_y_top = height - 2.2 * inch
    table_w = width - 1.6 * inch
    row_h = 0.48 * inch

    rows = [
        ("24h Cumulative Streams", summary.get("cumulative_windows", {}).get("24h", 0)),
        ("3 Day Cumulative Streams", summary.get("cumulative_windows", {}).get("3d", 0)),
        ("7 Day Cumulative Streams", summary.get("cumulative_windows", {}).get("7d", 0)),
        ("14 Day Cumulative Streams", summary.get("cumulative_windows", {}).get("14d", 0)),
        ("21 Day Cumulative Streams", summary.get("cumulative_windows", {}).get("21d", 0)),
        ("30 Day Cumulative Streams", summary.get("cumulative_windows", {}).get("30d", 0)),
        ("Cumulative Listeners", summary.get("latest_cumulative_listeners", 0)),
        ("Average Replay Rate", summary.get("avg_replay_rate", 0)),
        ("Average Save Rate", summary.get("avg_save_rate", 0)),
        ("Cumulative Saves", summary.get("latest_cumulative_saves", 0)),
        ("Cumulative Skips", summary.get("latest_cumulative_skips", 0)),
    ]

    pdf.setStrokeColor(GOLD)
    pdf.setFillColor(colors.HexColor("#1A1A1A"))

    for index, (label, value) in enumerate(rows):
        y = table_y_top - (index + 1) * row_h
        pdf.rect(table_x, y, table_w, row_h, stroke=1, fill=1)
        pdf.setFillColor(SOFT_GOLD)
        pdf.setFont("Helvetica", 11)
        pdf.drawString(table_x + 0.18 * inch, y + 0.16 * inch, str(label))
        pdf.setFillColor(GOLD)
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawRightString(table_x + table_w - 0.18 * inch, y + 0.16 * inch, str(value))
        pdf.setFillColor(colors.HexColor("#1A1A1A"))


def _draw_chart_page(pdf: canvas.Canvas, title: str, chart_path: str, width: float, height: float) -> None:
    _paint_background(pdf, width, height)
    _draw_header(pdf, title, "Generated by Local Music Release Reporter", width, height)
    image_x = 0.75 * inch
    image_y = 0.75 * inch
    image_w = width - 1.5 * inch
    image_h = height - 2.25 * inch
    pdf.drawImage(chart_path, image_x, image_y, width=image_w, height=image_h, preserveAspectRatio=True)


def generate_report_pdf(
    song: dict,
    report_day: int,
    report_name: str,
    summary: dict,
    chart_paths: dict[str, str],
    output_dir: Path,
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"{_slugify(song['title'])}_day_{report_day}_{timestamp}.pdf"
    output_path = output_dir / filename

    pdf = canvas.Canvas(str(output_path), pagesize=PAGE_SIZE)
    width, height = PAGE_SIZE

    _paint_background(pdf, width, height)
    _draw_header(
        pdf,
        f"{song['title']} | {report_name}",
        f"Release Date: {song['release_date']}  |  Spotify: {song['spotify_link']}",
        width,
        height,
    )
    _draw_summary_table(pdf, summary, width, height)
    pdf.showPage()

    _draw_chart_page(pdf, "Cumulative Streams + Listeners", chart_paths["performance"], width, height)
    pdf.showPage()

    _draw_chart_page(pdf, "Replay, Save, and Skip Behavior", chart_paths["engagement"], width, height)
    pdf.showPage()

    pdf.save()
    return output_path
